
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# DomBus modules connected to a Modbus RS485 bus
modbus: !include dombus/dombus1.yaml
# Another bus to connect other DomBus modules...
# modbus: !include dombus/dombus2.yaml
# Include template with some additional entities
template: !include dombus/dombus_template.yaml
# Include some automations and helpers for DomBusEVSE EV charging module
automation: !include dombus/dombusevse/dombusevse_automations.yaml
input_button: !include dombus/dombusevse/dombusevse_input_button.yaml
input_number: !include dombus/dombusevse/dombusevse_input_number.yaml
input_select: !include dombus/dombusevse/dombusevse_input_select.yaml

logger:
    default: warning
    logs:
        homeassistant.components.modbus: debug
        pymodbus: debug
        homeassistant.components.automation: warning
