# Set the EVMAXCURRENT parameter
- id: '1686869578501'
  alias: EVMaxCurrentAutomation
  trigger:
  - platform: state
    entity_id:
    - input_number.evmaxcurrent
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9001
      value: '{{ states(''input_number.evmaxcurrent'') | int }}'
  mode: single
# Set the EVMAXPOWER parameter
- id: '1686869578502'
  alias: EVMaxGridPowerAutomation
  trigger:
  - platform: state
    entity_id: input_number.evmaxgridpower
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9002
      value: '{{ states(''input_number.evmaxgridpower'') | int }}'
  mode: single
# Set the EVSTARTPOWER parameter
- id: '1686869578503'
  alias: EVStartPowerAutomation
  trigger:
  - platform: state
    entity_id: input_number.evstartpower
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9003
      value: '{{ states(''input_number.evstartpower'') | int }}'
  mode: single
# Set the EVSTOPTIME parameter
- id: '1686869578504'
  alias: EVStopTimeAutomation
  trigger:
  - platform: state
    entity_id: input_number.evstoptime
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9004
      value: '{{ states(''input_number.evstoptime'') | int }}'
  mode: single
# Set the EVAUTOSTART parameter
- id: '1686869578505'
  alias: EVAutoStartAutomation
  trigger:
  - platform: state
    entity_id: input_number.evautostart
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9005
      value: '{{ states(''input_number.evautostart'') | int }}'
  mode: single
# Set the EVMAXPOWER2 parameter
- id: '1686869578506'
  alias: EVMaxPower2
  trigger:
  - platform: state
    entity_id: input_number.evmaxpower2
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9006
      value: '{{ states(''input_number.evmaxpower2'') | int }}'
  mode: single
# Set the EVMAXPOWERTIME parameter
- id: '1686869578507'
  alias: EVMaxPowerTimeAutomation
  trigger:
  - platform: state
    entity_id: input_number.evmaxpowertime
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9007
      value: '{{ states(''input_number.evmaxpowertime'') | int }}'
  mode: single
# Set the EVMAXPOWERTIME2 parameter
- id: '1686869578508'
  alias: EVMaxPowerTime2Automation
  trigger:
  - platform: state
    entity_id: input_number.evmaxpowertime2
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9008
      value: '{{ states(''input_number.evmaxpowertime2'') | int }}'
  mode: single
# Set the EVWAITTIME parameter
- id: '1686869578509'
  alias: EVWaitTimeAutomation
  trigger:
  - platform: state
    entity_id: input_number.evwaittime
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 9009
      value: '{{ states(''input_number.evwaittime'') | int }}'
  mode: single
# Update the EVStateName entity with the name associated to EVState number (convert from numeric state to mnemonic)
- id: "evstatenameautomation"
  trigger:
  - platform: state
    entity_id: sensor.evstate
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.evstatename
        option: >
          {% set slist = state_attr('input_select.evstatename','options') %}
          {% set item = states.sensor.evstate.state|int %}
          {{slist[item]}}
# Update the EVModeName entity with the name associated to the current EVMode value (convert from numeric state to mnemonic)
- id: "evmodenameautomation"
  trigger:
  - platform: state
    entity_id: sensor.evmode
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.evmodename
        option: >
          {% set slist = state_attr('input_select.evmodename','options') %}
          {% set item = states.sensor.evmode.state|int %}
          {{slist[item]}}
# Update EVMode from EVModeName when button EVStateSet is pushed"
- id: "evmodenameautomationrev"
  trigger:
  - platform: state
    entity_id: input_button.evmodeset
  action:
    - service: modbus.write_register
      data:
        hub: dombus1
        slave: 227
        address: 3
        value: >
          {% set slist = state_attr('input_select.evmodename','options') %}
          {% set itemname = states.input_select.evmodename.state %}
          {% set itemnum = 0 %}
          {% for name in slist %}
            {% if name == itemname %}
              {{ loop.index0 }}
          {% endif %}
          {% endfor %}
# Set the GridPower EVSE entity with the current power sinked from the electrical grid
- id: 'evgridpowerautomation'
  alias: EVGridPowerAutomation
  trigger:
  - platform: state
# replace gridpower with name of your grid power meter entity 
    entity_id: sensor.gridpower
  action:
  - service: modbus.write_register
    data:
      hub: dombus1
      slave: 227
      address: 11
# replace gridpower with name of your grid power meter entity 
      value: >
        {% if states('sensor.gridpower')|int < 0 %}
          {{ 65536 + states('sensor.gridpower') | int }}
        {% else %}
          {{ states('sensor.gridpower') | int }}
        {% endif %}
  mode: single

